## What is a Tensor? - Part 2
**Synopsis:** In this notebook we will continue from where we left off in [Part 1](https://youtu.be/WdDVXMOQMss) of "What is a Tensor?". The main goal of this notebook is to demonstrate how to construct and use **scalars**, **vectors**, **matrices**, and eventually **tensors** of different dimensions. The tools used in this notebook are Python and Numpy. In addition, we will begin to introduce some notations, which will become useful for future programming sessions.

In [3]:
import numpy as np

### Scalar
A scalar represents a one-component quantity, such as a single number. 

Notation: $a$ - a scalar (integer or real)

![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vQT3NRFA6TMdbyxXQ2OtQ3byI2VUN5O2MzHocftU9q514D4_vJOs_2kGQjuUpkuB3mgU3rgQsWceVNY/pub?w=522&h=300)

In [4]:
### Declaring a scalar through python built in datatypes
a = 7

In [5]:
b = "string"

In [6]:
np.isscalar(a)

True

In [7]:
np.isscalar(b)

True

### Vector
A vector is a one-dimensional array of length n. n represents the number of scalar components.

Notation: $\boldsymbol a$ - a vector

![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vRV5XTFBiuOgGSbVPzj04U30IP2YDqqIorCRWADVr2c-xas0RjsihHS_tQ63FFMEGDdWk0CtpBis5y3/pub?w=543&h=214)

In [21]:
### creating a vector or 1-dimensional array using python builtin datatypes
v1 = [1,2,3,4,5]

In [22]:
print(v1)

[1, 2, 3, 4, 5]


In [23]:
print("The vector v1 is of n={} dimension".format(len(v1)))

The vector v1 is of n=5 dimension


In [24]:
### Creating a vector or 1-dimensional array with Numpy (Random numbers) ###
v2 = np.random.randn(1,5)
print(v2)

[[ 0.05288984 -1.06033546 -0.62888972 -2.1954612   1.17942183]]


In [25]:
v2.shape

(1, 5)

In [26]:
print("The vector v2 is of {} by {} dimension".format(v2.shape[0], v2.shape[1]))

The vector v2 is of 1 by 5 dimension


In [27]:
### Creating a vector or 1-dimensional array with numpy (fixed values) ###
v3 = np.array([[1,2,3,4,5]])
print(v3)

[[1 2 3 4 5]]


In [28]:
v3.shape

(1, 5)

In [29]:
print("The vector v3 is of {} by {} dimension".format(v3.shape[0], v3.shape[1]))

The vector v3 is of 1 by 5 dimension


![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vTzbktCb3GAd5BekSjd67tYZaZHVHci2a0_V6yUlRPonls5hAI3cHPkVOgKKhk5wglnKkp-lVTLVVAQ/pub?w=524&h=252)

In [30]:
### Obtaining elements in (i) position (Classic approach) - this is a scalar component ###
position = 3
print("The element in position {} of vector v1 is {}".format(position, v1[position-1]))

The element in position 3 of vector v1 is 3


In [31]:
### Obtaining elements in (i) position (numpy) - this is a scalar component ###
position = 3
print("The element in position {} of vector v2 is {}".format(position, v2[:,position-1]))

The element in position 3 of vector v2 is [-0.62888972]


In [32]:
print(v2)

[[ 0.05288984 -1.06033546 -0.62888972 -2.1954612   1.17942183]]


In [33]:
### Obtaining elements in (i) position (numpy) - this is a scalar component ###
position = 3
print("The element in position {} of vector v3 is {}".format(position, v3[:,position-1]))

The element in position 3 of vector v3 is [3]


---

### Matrix
A matrix is a 2-D array of numbers. A matrix is also made up of scalars and vectors. 

Notation: $\boldsymbol A$ - a matrix A with $m$ rows, $n$ columns, where $\boldsymbol A=\mathbb R^{m\times n}$.

![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vRkbIyENJgIlKRSC5wL-m-Fwl3-7svFtNy-VyaRzGQ6l6OPOxO0ZT-B0BEbMUQRVwNTusPG2h8OMKeA/pub?w=391&h=412)

In [34]:
### Creating a matrix or 2D array using python built-in datatypes
A = [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20], 
     [21,22,23,24,25]]
print(A)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [35]:
print("The matrix A has a dimension of {} by {}".format(len(A), len(A[0])))

The matrix A has a dimension of 5 by 5


In [36]:
### Creating a matrix or 2D array using numpy ###
B = np.array([[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20], 
     [21,22,23,24,25]])
print(B)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [37]:
B.shape

(5, 5)

In [38]:
print("The matrix B has a dimenion of {} by {}".format(B.shape[0], B.shape[1]))

The matrix B has a dimenion of 5 by 5


In [39]:
B = np.random.randn(5,5)
print(B)

[[ 0.15700336 -1.20023447 -1.38608987  1.3173295   1.84865146]
 [ 1.13034553  0.64396451 -0.91495254  0.38178023  1.5845806 ]
 [ 0.90335004 -0.75512874  0.95059692  1.96264102  0.79136834]
 [-0.39934131  0.93625109  0.21566024 -1.26672168 -0.14441973]
 [-0.89248777  0.31069237 -0.90021293 -0.22804121 -0.17833299]]


In [40]:
B.shape

(5, 5)

In [41]:
print("The matrix B has a dimenion of {} by {}".format(B.shape[0], B.shape[1]))

The matrix B has a dimenion of 5 by 5


![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vQYM2jzmHcduY-Th3mplCx0e1Ha-iR9wIhP6-ruVWz1GT1KwU-mr-YsrtdL4Fv0fJ1FzcANhIunYlUt/pub?w=521&h=631)

In [42]:
### Print the 3rd column (column vector indexed at position 3) of the 2D-matrix (classic approach) ###
position = 3
for i in range(len(A)): # [0, 1, 2, 3, 4]
    for j in range(len(A[0])): # [0, 1, 2, 3, 4]
        if j == (position-1):
            print(A[i][j])

3
8
13
18
23


In [43]:
print(A)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [44]:
### Print the 3rd column (column vector indexed at position 3) of the 2D-matrix using numpy ###
position = 3
print(B[:, (position-1)])

[-1.38608987 -0.91495254  0.95059692  0.21566024 -0.90021293]


In [45]:
print(B)

[[ 0.15700336 -1.20023447 -1.38608987  1.3173295   1.84865146]
 [ 1.13034553  0.64396451 -0.91495254  0.38178023  1.5845806 ]
 [ 0.90335004 -0.75512874  0.95059692  1.96264102  0.79136834]
 [-0.39934131  0.93625109  0.21566024 -1.26672168 -0.14441973]
 [-0.89248777  0.31069237 -0.90021293 -0.22804121 -0.17833299]]


**Exercise:** Make selection of 2 columns using both the classic approach and numpy approach.

![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vQJ6a2memE5EvGLjwcB2yIQKm5NMzcUdZ1xEUFgQNkzkKWySMpoZ88lRopn6RoHJ-sHfxYEdrfmf2Tc/pub?w=685&h=589)

In [46]:
### Print the 4th row (row vector indexed at position 4) of the 2D-matrix (classic approach) ###
position = 4
for i in range(len(A)): # [0, 1, 2, 3, 4]
    for j in range(len(A[0])): # [0, 1, 2, 3, 4]
        if i == (position-1):
            print(A[i][j])

16
17
18
19
20


In [47]:
print(A)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [48]:
### Print the 4th row (row vector index at position 4) of the 2D-matrix using numpy ###
position = 4
print(B[ (position-1), : ])

[-0.39934131  0.93625109  0.21566024 -1.26672168 -0.14441973]


In [49]:
print(B)

[[ 0.15700336 -1.20023447 -1.38608987  1.3173295   1.84865146]
 [ 1.13034553  0.64396451 -0.91495254  0.38178023  1.5845806 ]
 [ 0.90335004 -0.75512874  0.95059692  1.96264102  0.79136834]
 [-0.39934131  0.93625109  0.21566024 -1.26672168 -0.14441973]
 [-0.89248777  0.31069237 -0.90021293 -0.22804121 -0.17833299]]


**Exercise:** Make selection of 2 rows using both the classic approach and numpy approach.

![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vQ5mQOxyoEs5R87COmv20SKxAG2sMFtc6lly2r4R5Cgjn4oSCTCXqWodrQajmYJS5HOPOkmKnf9oDMI/pub?w=520&h=629)

In [50]:
### Print scalar component positioned at row 3 and column 3 ###
row_index = 3
col_index = 3

for i in range(len(A)): #range of # of rows
    for j in range(len(A[0])): #range of # of cols
        if i == (row_index-1) and j == (col_index-1):
            print(A[i][j])

13


In [51]:
print(A)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [52]:
A[row_index-1][col_index-1]

13

In [53]:
B[row_index-1][col_index-1]

0.95059692460915535

In [54]:
print(B)

[[ 0.15700336 -1.20023447 -1.38608987  1.3173295   1.84865146]
 [ 1.13034553  0.64396451 -0.91495254  0.38178023  1.5845806 ]
 [ 0.90335004 -0.75512874  0.95059692  1.96264102  0.79136834]
 [-0.39934131  0.93625109  0.21566024 -1.26672168 -0.14441973]
 [-0.89248777  0.31069237 -0.90021293 -0.22804121 -0.17833299]]


![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vShF3GIMqXhaAqE7NcS01U2RdzcC1xlCDPev55ULh0ZCneAJLzmE_LRSnphGGNlRZoUrrACkHyMnpLG/pub?w=518&h=564)

**Exercise:** Extract the values highlighted in the figure above from both matrix A and B. 

---

### Tensor
A tensor is just a generalization of vectors and matrices.

Notation: $\mathsf A$ - a tensor

![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vQ5mtG-AkGF0GmblhUgl3iHh5WwZrvCxxSRmHgHfVamCMyrsx22Ws7s21cAzwaJBZn5csSpPTZ_dIdq/pub?w=557&h=542)

In [59]:
### Constructing a 3D-tensor using classic approach ###
C = [[[1,2,3,4,5], # begining of 1st matrix
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20], 
     [21,22,23,24,25]],
     [[26,27,28,29,30], # beginning of 2nd matrix
     [31,32,33,34,35],
     [36,37,38,39,40],
     [41,42,43,44,45], 
     [46,47,48,49,50]],
     [[51,52,53,54,55], # beginning of 3rd matrix
     [56,57,58,59,60],
     [61,62,63,64,65],
     [66,67,68,69,70], 
     [71,72,73,74,75]],
     [[76,77,78,79,80], # beginning of 4th matrix
     [81,82,83,84,85],
     [86,87,88,89,90],
     [91,92,93,94,95], 
     [96,97,98,99,100]],
     [[101,102,103,104,105], # beginning of 5th matrix
     [106,107,108,109,110],
     [111,112,113,114,115],
     [116,117,118,119,120], 
     [121,122,123,124,125]]]
print(C)

[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]], [[26, 27, 28, 29, 30], [31, 32, 33, 34, 35], [36, 37, 38, 39, 40], [41, 42, 43, 44, 45], [46, 47, 48, 49, 50]], [[51, 52, 53, 54, 55], [56, 57, 58, 59, 60], [61, 62, 63, 64, 65], [66, 67, 68, 69, 70], [71, 72, 73, 74, 75]], [[76, 77, 78, 79, 80], [81, 82, 83, 84, 85], [86, 87, 88, 89, 90], [91, 92, 93, 94, 95], [96, 97, 98, 99, 100]], [[101, 102, 103, 104, 105], [106, 107, 108, 109, 110], [111, 112, 113, 114, 115], [116, 117, 118, 119, 120], [121, 122, 123, 124, 125]]]


In [60]:
print("The tensor C has a dimension of {} by {} by {}".format(len(C), len(C[0]), len(C[1])))

The tensor C has a dimension of 5 by 5 by 5


In [62]:
### Constructing a 3D-tensor using numpy approach ###
D = np.array([[[1,2,3,4,5], # begining of 1st matrix
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20], 
     [21,22,23,24,25]],
     [[26,27,28,29,30], # beginning of 2nd matrix
     [31,32,33,34,35],
     [36,37,38,39,40],
     [41,42,43,44,45], 
     [46,47,48,49,50]],
     [[51,52,53,54,55], # beginning of 3rd matrix
     [56,57,58,59,60],
     [61,62,63,64,65],
     [66,67,68,69,70], 
     [71,72,73,74,75]],
     [[76,77,78,79,80], # beginning of 4th matrix
     [81,82,83,84,85],
     [86,87,88,89,90],
     [91,92,93,94,95], 
     [96,97,98,99,100]],
     [[101,102,103,104,105], # beginning of 5th matrix
     [106,107,108,109,110],
     [111,112,113,114,115],
     [116,117,118,119,120], 
     [121,122,123,124,125]]])
print(D)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]]

 [[ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]]

 [[ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]

 [[101 102 103 104 105]
  [106 107 108 109 110]
  [111 112 113 114 115]
  [116 117 118 119 120]
  [121 122 123 124 125]]]


In [63]:
D.shape

(5, 5, 5)

In [64]:
print("The tensor D has a dimension of {} by {} by {}".format(D.shape[0], D.shape[1], D.shape[2]))

The tensor D has a dimension of 5 by 5 by 5


![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vRtpLZSs3M1Sf26sx2VZFBxCoBHaOPAy-YlOd2KzxQvbExouY1h37rJHvoIa44fL7QrYnFblIDcGbmU/pub?w=549&h=498)

In [65]:
### Extract a specific matrix from a 3d tensor built with numpy ###
D[ 3, : , :]

array([[ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [66]:
print(D)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]]

 [[ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]]

 [[ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]

 [[101 102 103 104 105]
  [106 107 108 109 110]
  [111 112 113 114 115]
  [116 117 118 119 120]
  [121 122 123 124 125]]]


![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vT9ZmGiYCbks-xD2aYb7OQ8tmzAcKO8YWqXEmK69MNRhMjeXLFSfpOddiRibty2P4usU58kOYlGMfcg/pub?w=555&h=504)

In [71]:
D[:, 1, 4]

array([ 10,  35,  60,  85, 110])

In [72]:
print(D)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]]

 [[ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]]

 [[ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]

 [[101 102 103 104 105]
  [106 107 108 109 110]
  [111 112 113 114 115]
  [116 117 118 119 120]
  [121 122 123 124 125]]]


![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vSs8us1T8DFJnXnCI1SJnAzWSBZFl0ODNMD7z-8aUi-dCatcZGpCTLAzt6WpGBbM9y3zQ58SjvPMliq/pub?w=543&h=495)

In [73]:
D[2 , 0 , 2]

53

In [74]:
print(D)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [ 11  12  13  14  15]
  [ 16  17  18  19  20]
  [ 21  22  23  24  25]]

 [[ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]
  [ 41  42  43  44  45]
  [ 46  47  48  49  50]]

 [[ 51  52  53  54  55]
  [ 56  57  58  59  60]
  [ 61  62  63  64  65]
  [ 66  67  68  69  70]
  [ 71  72  73  74  75]]

 [[ 76  77  78  79  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]
  [ 96  97  98  99 100]]

 [[101 102 103 104 105]
  [106 107 108 109 110]
  [111 112 113 114 115]
  [116 117 118 119 120]
  [121 122 123 124 125]]]


![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vQwnyBMOH0IDZwfOMWeih-UnLqfZe-JMnJ64qhGUBOdgM9w6FJY23DQKiarUjzsX9-k2lK1-6gqfo-C/pub?w=562&h=505)

**Exercise:** Extract the selected column vectors from the tensor D, just as shown in the figure above.